<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../receivePO.wsdl"/>
      <rootElement name="PurchaseOrder" namespace="http://xmlns.oracle.com/ns/order"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../OrdersBAMAdapter.wsdl"/>
      <rootElement name="_Orders1Collection" namespace="http://xmlns.oracle.com/bam"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [WED MAR 11 21:09:58 IST 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:tns="http://oracle.com/sca/soapservice/POProcessing/POProcessing/receivePO"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:imp1="http://xmlns.oracle.com/bam"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/bam/POProcessing/POProcessing/OrdersBAMAdapter"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:inp1="http://xmlns.oracle.com/ns/order"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns inp1 xsd wsdl imp1 ns0 plt xp20 bpws mhdr bpel oraext dvm hwf med ids bpm xdk xref ora socket ldap">
  <xsl:template match="/">
    <imp1:_Orders1Collection>
      <imp1:_Orders1>
        <imp1:_Order_ID>
          <xsl:value-of select="/inp1:PurchaseOrder/inp1:ID"/>
        </imp1:_Order_ID>
        <imp1:_Customer_ID>
          <xsl:value-of select="/inp1:PurchaseOrder/inp1:CustID"/>
        </imp1:_Customer_ID>
        <imp1:_Product_Name>
          <xsl:value-of select="/inp1:PurchaseOrder/inp1:productName"/>
        </imp1:_Product_Name>
        <imp1:_Item_Type>
          <xsl:value-of select="/inp1:PurchaseOrder/inp1:itemType"/>
        </imp1:_Item_Type>
        <imp1:_Price>
          <xsl:value-of select="/inp1:PurchaseOrder/inp1:price"/>
        </imp1:_Price>
        <imp1:_Quantity>
          <xsl:value-of select="/inp1:PurchaseOrder/inp1:quantity"/>
        </imp1:_Quantity>
        <imp1:_Status>
          <xsl:value-of select="/inp1:PurchaseOrder/inp1:status"/>
        </imp1:_Status>
      </imp1:_Orders1>
    </imp1:_Orders1Collection>
  </xsl:template>
</xsl:stylesheet>
